config/routes.rb
Bills::Application.routes.draw do
  devise_for :users
  
  namespace :admin do
    resources :containers
  end

   root :to => 'admin::containers#index'

end

app/models/container.rb
class Container < ActiveRecord::Base
  # attr_accessible :title, :body
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  
  validates :username, :uniqueness => true,
          :length => { :within => 4..12 }
  protected
def self.find_for_database_authentication(warden_conditions)
  conditions = warden_conditions.dup
  login = conditions.delete(:name) 
  where(conditions).where(["lower(name) = :value", { :value => login.downcase }]).first
end
end

app/controllers/admin/containers_controller.rb
class Admin::ContainersController < ApplicationController
before_filter :authenticate_user!

def index
  @containers = Container.all
end

def new
  @container = Container.new  
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  protect_from_forgery
  
end

app/helpers/admin/containers_helper.rb
module Admin::ContainersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/containers/index.erb
<div style="float: right">
	<%= link_to "New Container", new_admin_container_path%>
</div>
<div>
	<table id = "rounded-corner">
		<thead>
		<tr>
			<th class="rounded-company">S.No</th>
			<th>Name </th>
		</tr>
		</thead>
		<% @containers.each do |con| %>
		<tr>
			<td>1</td>
			<td><%= con.name %></td>
		</tr>
		<% end %>
	</table>
</div>

app/views/admin/containers/new.html.erb
<div>
	<%= form_for :container, :action => {:url => "create"} do |contain|%>
	<%= contain.label :name%>
	<%= contain.text_field :name %> <br/>
	<%= contain.label :status%>
	
	<% end %>
</div>

app/views/layouts/_menus.html.erb
 <ul class="menu">
        <li><a href="#" class="parent top"><span>Home</span></a>
            <ul>
                <li><a href="#" class="parent"><span>Sub Item 1</span></a>
                    <ul>                       
                        <li><a href="#" class="parent"><span>Sub Item 1.1</span></a>
                            <ul>
                                <li><a href="#"><span>Sub Item 1.1.1</span></a></li>
                                <li><a href="#"><span>Sub Item 1.1.2</span></a></li>
                            </ul>
                        </li>
                        <li><a href="#"><span>Sub Item 1.2</span></a></li>
                        <li><a href="#"><span>Sub Item 1.3</span></a></li>
                        <li><a href="#"><span>Sub Item 1.4</span></a></li>
                        <li><a href="#"><span>Sub Item 1.5</span></a></li>
                        <li><a href="#"><span>Sub Item 1.6</span></a></li>
                        <li><a href="#" class="parent"><span>Sub Item 1.7</span></a>
                            <ul>
                                <li><a href="#"><span>Sub Item 1.7.1</span></a></li>
                                <li><a href="#"><span>Sub Item 1.7.2</span></a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li><a href="#"><span>Sub Item 2</span></a></li>
                <li><a href="#"><span>Sub Item 3</span></a></li>
            </ul>
        </li>
        <li><a href="#" class="parent top"><span>Product Info</span></a>
            <ul>
                <li><a href="#" class="parent"><span>Sub Item 1</span></a>
                    <ul>
                        <li><a href="#"><span>Sub Item 1.1</span></a></li>
                        <li><a href="#"><span>Sub Item 1.2</span></a></li>
                    </ul>
                </li>
                <li><a href="#" class="parent"><span>Sub Item 2</span></a>
                    <ul>
                        <li><a href="#"><span>Sub Item 2.1</span></a></li>
                        <li><a href="#"><span>Sub Item 2.2</span></a></li>
                    </ul>
                </li>
                <li><a href="#"><span>Sub Item 3</span></a></li>
                <li><a href="#"><span>Sub Item 4</span></a></li>
                <li><a href="#"><span>Sub Item 5</span></a></li>
                <li><a href="#"><span>Sub Item 6</span></a></li>
                <li><a href="#"><span>Sub Item 7</span></a></li>
            </ul>
        </li>
        <li><a href="#" class="top"><span>Help</span></a></li>
        <li class="last"><a href="#" class="top"><span>Contacts</span></a></li>
    </ul>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bills</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
  <style type="text/css">
/*demo page css*/
p{ font: 70% "Trebuchet MS", sans-serif; margin: 8px;}
.demoHeaders { margin-top: 2em; }
#dialog_link {padding: .4em 1em .4em 20px;text-decoration: none;position: relative;}
#dialog_link span.ui-icon {margin: 0 5px 0 0;position: absolute;left: .2em;top: 50%;margin-top: -8px;}
ul#icons {margin: 0; padding: 0;}
ul#icons li {margin: 2px; position: relative; padding: 4px 0; cursor: pointer; float: left; list-style: none;}
ul#icons span.ui-icon {float: left; margin: 0 4px;}
</style>
</head>
<body style="background-color: #E0E5F5 "> 
	<div style="float:right; color:white"><%if user_signed_in?%>
		Hi <%= current_user.name%> | <%= link_to "sign out", destroy_user_session_path, :method => :delete %> <% end %>
	</div>

	<div style="height:15px; background-color: #3B5998 ; color: white;  text-align: center; padding: 20px 0;" >ABC Pvt. Ltd  </div>
	
	 
	<div id="menu"> <%= render :partial=> "layouts/menus"%> </div>
	<% if notice%>
	<div class='ui-widget'>
	<div class='ui-state-highlight ui-corner-all' style="margin-top: 2px; padding: 0 .7em;">
		<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
	<%= notice %></p></div></div>
<%end%>
<div class="container">

<div class="right">

     <%= yield %>

</div>
</div>
</body>
<script>
document.write('<div style="display:none;"><a href="http://apycom.com/">jQuery Menu by Apycom</a></div>');
</script>
</html>
					